---
# cr660x (MT7981)

# ── WiFi radios ──
radio0:
  band: "2g"
  channel: "auto"
  htmode: "HE20"
  txpower: 20

radio1:
  band: "5g"
  channel: "auto"
  htmode: "HE80"
  txpower: 10

# ── SSIDs ──
ssids:
  camera:
    radio: "radio0"
    ssid: "OpenWrt_Camera"
    encryption: "psk2"
    key: "!$EhvbqFR5AV2&V"
    vlan: "camera"
    isolate: true
    ieee80211r: true
    mobility_domain: "caca"
    ft_over_ds: false
    ft_psk_generate_local: true
    dtim_period: 3

  iot:
    radio: "radio0"
    ssid: "OpenWrt_IoT"
    encryption: "psk2"
    key: "VFtw!a%Vby4yNDzH"
    vlan: "iot"
    isolate: true
    ieee80211r: true
    mobility_domain: "abab"
    ft_over_ds: false
    ft_psk_generate_local: true
    dtim_period: 3

  guest:
    radio: "radio0"
    ssid: "OpenWrt_Guest"
    encryption: "psk2"
    key: "12345679"
    vlan: "guest"
    isolate: true
    ieee80211r: true
    mobility_domain: "adad"
    ft_over_ds: false
    ft_psk_generate_local: true
    dtim_period: 3

  home:
    radio: "radio1"
    ssid: "OpenWrt_Home"
    encryption: "sae"
    key: "uGMzq*P%g327"
    vlan: "home"
    ieee80211r: true
    mobility_domain: "efef"
    ft_over_ds: false
    ocv: 0
    dtim_period: 3
